// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// {@template vpn_manager_state}
/// Current state of the platform VPN engine.
///
/// This enum models the high-level lifecycle of the VPN service/engine as seen
/// from Dart. Implementations may have additional internal substates; they should
/// be mapped onto these public states in a consistent way.
///
/// ## Typical state flow
/// - [disconnected] → [connecting] → [connected]
/// - On transient failure: [connected] → [waitingForRecovery] → [recovering]
/// - When network is unavailable: [connecting] or [recovering] → [waitingForNetwork]
///
/// The exact transitions and timing depend on the platform implementation.
/// {@endtemplate}
enum VpnManagerState {
  disconnected,
  connecting,
  connected,
  waitingForRecovery,
  recovering,
  waitingForNetwork,
}

/// {@template platform_error_code}
/// High-level error category returned by platform implementations.
///
/// This is intended for coarse error classification suitable for UI messaging
/// and analytics. More specific errors may be provided via [PlatformFieldError].
/// {@endtemplate}
enum PlatformErrorCode {
  unknown,
}

/// {@template platform_field_error_code}
/// Error category for a specific user-visible field.
///
/// Field errors are typically used to attach validation errors to individual
/// configuration inputs (e.g. invalid IP address).
/// {@endtemplate}
enum PlatformFieldErrorCode {
  fieldWrongValue,
  alreadyExists,
}

/// {@template platform_field_name}
/// Identifies which input field a [PlatformFieldError] refers to.
///
/// The field set is intentionally limited to values that are meaningful to
/// external consumers and stable across platforms.
/// {@endtemplate}
enum PlatformFieldName {
  ipAddress,
  domain,
  serverName,
  dnsServers,
}

/// {@template platform_error_response}
/// Structured error payload returned by platform implementations.
///
/// This model supports two levels of error reporting:
/// - a top-level [code] for general classification,
/// - optional per-field validation errors in [fieldErrors].
///
/// Both fields are nullable to support platforms that only provide partial
/// error information.
/// {@endtemplate}
class PlatformErrorResponse {
  PlatformErrorResponse({
    this.code,
    this.fieldErrors,
  });

  /// {@template platform_error_response_code}
  /// General error category, if available.
  /// {@endtemplate}
  PlatformErrorCode? code;

  /// {@template platform_error_response_field_errors}
  /// Optional list of validation errors tied to individual fields.
  /// {@endtemplate}
  List<PlatformFieldError?>? fieldErrors;

  List<Object?> _toList() {
    return <Object?>[
      code,
      fieldErrors,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformErrorResponse decode(Object result) {
    result as List<Object?>;
    return PlatformErrorResponse(
      code: result[0] as PlatformErrorCode?,
      fieldErrors: (result[1] as List<Object?>?)?.cast<PlatformFieldError?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformErrorResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// {@template platform_field_error}
/// Validation error associated with a particular configuration field.
///
/// A field error specifies:
/// - [code] describing the kind of failure,
/// - [fieldName] identifying which field is invalid.
///
/// This structure is designed for UI clients that want to show inline
/// validation messages next to problematic fields.
/// {@endtemplate}
class PlatformFieldError {
  PlatformFieldError({
    required this.code,
    required this.fieldName,
  });

  /// {@template platform_field_error_code_field}
  /// Category of the field error.
  /// {@endtemplate}
  PlatformFieldErrorCode code;

  /// {@template platform_field_error_field_name}
  /// Which field the error relates to.
  /// {@endtemplate}
  PlatformFieldName fieldName;

  List<Object?> _toList() {
    return <Object?>[
      code,
      fieldName,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformFieldError decode(Object result) {
    result as List<Object?>;
    return PlatformFieldError(
      code: result[0]! as PlatformFieldErrorCode,
      fieldName: result[1]! as PlatformFieldName,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformFieldError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VpnManagerState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformErrorCode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformFieldErrorCode) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PlatformFieldName) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PlatformErrorResponse) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformFieldError) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnManagerState.values[value];
      case 130: 
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformErrorCode.values[value];
      case 131: 
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformFieldErrorCode.values[value];
      case 132: 
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformFieldName.values[value];
      case 133: 
        return PlatformErrorResponse.decode(readValue(buffer)!);
      case 134: 
        return PlatformFieldError.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// {@template i_vpn_manager}
/// Host-side VPN manager API.
///
/// `IVpnManager` is implemented on the platform (host) side and called from Dart.
/// It provides the minimal lifecycle operations required by the plugin:
/// - [start] to start the VPN engine using a prepared configuration string.
/// - [stop] to stop the VPN engine.
/// - [getCurrentState] to query the current engine state.
///
/// ## Ordering and concurrency
/// [start] and [stop] are executed on a serial background queue (see [TaskQueue]).
/// This ensures:
/// - operations are performed in the order they are invoked,
/// - platform UI threads are not blocked by long-running operations.
///
/// ## Configuration format
/// The [config] parameter is a backend configuration document (string).
/// Its exact format is defined by the backend and produced on the Dart side
/// (for example by a [ConfigurationEncoder]).
/// {@endtemplate}
class IVpnManager {
  /// Constructor for [IVpnManager].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IVpnManager({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// {@template i_vpn_manager_start}
  /// Starts the VPN engine using the provided configuration document.
  ///
  /// [config] must contain a complete backend configuration text. The platform
  /// implementation is responsible for:
  /// - parsing/validating the configuration,
  /// - initiating any required permissions or service start,
  /// - transitioning the engine state accordingly.
  ///
  /// This call is executed on a serial background task queue to avoid blocking
  /// the platform UI thread.
  /// {@endtemplate}
  Future<void> start({required String serverName, required String config}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_plugin.IVpnManager.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serverName, config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// {@template i_vpn_manager_stop}
  /// Stops the VPN engine.
  ///
  /// The platform implementation should stop the underlying VPN service/process
  /// and transition the engine state to [VpnManagerState.disconnected].
  ///
  /// This call is executed on a serial background task queue to avoid blocking
  /// the platform UI thread.
  /// {@endtemplate}
  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_plugin.IVpnManager.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// {@template i_vpn_manager_update_configuration}
  /// Updates the iOS system VPN profile or deletes it.
  ///
  /// The platform implementation should update the iOS system VPN profile
  /// if the [serverName] and [config] are specified or delete the profile
  /// entirely if one of them is `null`.
  ///
  /// This method should always be called on stopped VPN engine.
  ///
  /// This call is executed on a serial background task queue to avoid blocking
  /// the platform UI thread.
  /// {@endtemplate}
  Future<void> updateConfiguration({String? serverName, String? config}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_plugin.IVpnManager.updateConfiguration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[serverName, config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// {@template i_vpn_manager_get_current_state}
  /// Returns the current VPN engine state.
  ///
  /// This method is typically used to:
  /// - restore UI state after app restart,
  /// - confirm whether a start/stop request has taken effect,
  /// - diagnose platform-side lifecycle issues.
  /// {@endtemplate}
  Future<VpnManagerState> getCurrentState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_plugin.IVpnManager.getCurrentState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as VpnManagerState?)!;
    }
  }
}

class IDeepLink {
  /// Constructor for [IDeepLink].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IDeepLink({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> decode({required String uri}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.vpn_plugin.IDeepLink.decode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[uri]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }
}
