// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PLATFORM_API_G_H_
#define PIGEON_PLATFORM_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace vpn_plugin {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class IVpnManager;
  friend class IDeepLink;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// {@template vpn_manager_state}
// Current state of the platform VPN engine.
//
// This enum models the high-level lifecycle of the VPN service/engine as seen
// from Dart. Implementations may have additional internal substates; they should
// be mapped onto these public states in a consistent way.
//
// ## Typical state flow
// - [disconnected] → [connecting] → [connected]
// - On transient failure: [connected] → [waitingForRecovery] → [recovering]
// - When network is unavailable: [connecting] or [recovering] → [waitingForNetwork]
//
// The exact transitions and timing depend on the platform implementation.
// {@endtemplate}
enum class VpnManagerState {
  kDisconnected = 0,
  kConnecting = 1,
  kConnected = 2,
  kWaitingForRecovery = 3,
  kRecovering = 4,
  kWaitingForNetwork = 5
};

// {@template platform_error_code}
// High-level error category returned by platform implementations.
//
// This is intended for coarse error classification suitable for UI messaging
// and analytics. More specific errors may be provided via [PlatformFieldError].
// {@endtemplate}
enum class PlatformErrorCode {
  kUnknown = 0
};

// {@template platform_field_error_code}
// Error category for a specific user-visible field.
//
// Field errors are typically used to attach validation errors to individual
// configuration inputs (e.g. invalid IP address).
// {@endtemplate}
enum class PlatformFieldErrorCode {
  kFieldWrongValue = 0,
  kAlreadyExists = 1
};

// {@template platform_field_name}
// Identifies which input field a [PlatformFieldError] refers to.
//
// The field set is intentionally limited to values that are meaningful to
// external consumers and stable across platforms.
// {@endtemplate}
enum class PlatformFieldName {
  kIpAddress = 0,
  kDomain = 1,
  kServerName = 2,
  kDnsServers = 3
};


// {@template platform_error_response}
// Structured error payload returned by platform implementations.
//
// This model supports two levels of error reporting:
// - a top-level [code] for general classification,
// - optional per-field validation errors in [fieldErrors].
//
// Both fields are nullable to support platforms that only provide partial
// error information.
// {@endtemplate}
//
// Generated class from Pigeon that represents data sent in messages.
class PlatformErrorResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  PlatformErrorResponse();

  // Constructs an object setting all fields.
  explicit PlatformErrorResponse(
    const PlatformErrorCode* code,
    const flutter::EncodableList* field_errors);

  // {@template platform_error_response_code}
  // General error category, if available.
  // {@endtemplate}
  const PlatformErrorCode* code() const;
  void set_code(const PlatformErrorCode* value_arg);
  void set_code(const PlatformErrorCode& value_arg);

  // {@template platform_error_response_field_errors}
  // Optional list of validation errors tied to individual fields.
  // {@endtemplate}
  const flutter::EncodableList* field_errors() const;
  void set_field_errors(const flutter::EncodableList* value_arg);
  void set_field_errors(const flutter::EncodableList& value_arg);

 private:
  static PlatformErrorResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class IVpnManager;
  friend class IDeepLink;
  friend class PigeonInternalCodecSerializer;
  std::optional<PlatformErrorCode> code_;
  std::optional<flutter::EncodableList> field_errors_;
};


// {@template platform_field_error}
// Validation error associated with a particular configuration field.
//
// A field error specifies:
// - [code] describing the kind of failure,
// - [fieldName] identifying which field is invalid.
//
// This structure is designed for UI clients that want to show inline
// validation messages next to problematic fields.
// {@endtemplate}
//
// Generated class from Pigeon that represents data sent in messages.
class PlatformFieldError {
 public:
  // Constructs an object setting all fields.
  explicit PlatformFieldError(
    const PlatformFieldErrorCode& code,
    const PlatformFieldName& field_name);

  // {@template platform_field_error_code_field}
  // Category of the field error.
  // {@endtemplate}
  const PlatformFieldErrorCode& code() const;
  void set_code(const PlatformFieldErrorCode& value_arg);

  // {@template platform_field_error_field_name}
  // Which field the error relates to.
  // {@endtemplate}
  const PlatformFieldName& field_name() const;
  void set_field_name(const PlatformFieldName& value_arg);

 private:
  static PlatformFieldError FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class IVpnManager;
  friend class IDeepLink;
  friend class PigeonInternalCodecSerializer;
  PlatformFieldErrorCode code_;
  PlatformFieldName field_name_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// {@template i_vpn_manager}
// Host-side VPN manager API.
//
// `IVpnManager` is implemented on the platform (host) side and called from Dart.
// It provides the minimal lifecycle operations required by the plugin:
// - [start] to start the VPN engine using a prepared configuration string.
// - [stop] to stop the VPN engine.
// - [getCurrentState] to query the current engine state.
//
// ## Ordering and concurrency
// [start] and [stop] are executed on a serial background queue (see [TaskQueue]).
// This ensures:
// - operations are performed in the order they are invoked,
// - platform UI threads are not blocked by long-running operations.
//
// ## Configuration format
// The [config] parameter is a backend configuration document (string).
// Its exact format is defined by the backend and produced on the Dart side
// (for example by a [ConfigurationEncoder]).
// {@endtemplate}
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class IVpnManager {
 public:
  IVpnManager(const IVpnManager&) = delete;
  IVpnManager& operator=(const IVpnManager&) = delete;
  virtual ~IVpnManager() {}
  // {@template i_vpn_manager_start}
  // Starts the VPN engine using the provided configuration document.
  //
  // [config] must contain a complete backend configuration text. The platform
  // implementation is responsible for:
  // - parsing/validating the configuration,
  // - initiating any required permissions or service start,
  // - transitioning the engine state accordingly.
  //
  // This call is executed on a serial background task queue to avoid blocking
  // the platform UI thread.
  // {@endtemplate}
  virtual std::optional<FlutterError> Start(
    const std::string& server_name,
    const std::string& config) = 0;
  // {@template i_vpn_manager_stop}
  // Stops the VPN engine.
  //
  // The platform implementation should stop the underlying VPN service/process
  // and transition the engine state to [VpnManagerState.disconnected].
  //
  // This call is executed on a serial background task queue to avoid blocking
  // the platform UI thread.
  // {@endtemplate}
  virtual std::optional<FlutterError> Stop() = 0;
  // {@template i_vpn_manager_update_configuration}
  // Updates the iOS system VPN profile or deletes it.
  //
  // The platform implementation should update the iOS system VPN profile
  // if the [serverName] and [config] are specified or delete the profile
  // entirely if one of them is `null`.
  //
  // This method should always be called on stopped VPN engine.
  //
  // This call is executed on a serial background task queue to avoid blocking
  // the platform UI thread.
  // {@endtemplate}
  virtual std::optional<FlutterError> UpdateConfiguration(
    const std::string* server_name,
    const std::string* config) = 0;
  // {@template i_vpn_manager_get_current_state}
  // Returns the current VPN engine state.
  //
  // This method is typically used to:
  // - restore UI state after app restart,
  // - confirm whether a start/stop request has taken effect,
  // - diagnose platform-side lifecycle issues.
  // {@endtemplate}
  virtual ErrorOr<VpnManagerState> GetCurrentState() = 0;

  // The codec used by IVpnManager.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `IVpnManager` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    IVpnManager* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    IVpnManager* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  IVpnManager() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class IDeepLink {
 public:
  IDeepLink(const IDeepLink&) = delete;
  IDeepLink& operator=(const IDeepLink&) = delete;
  virtual ~IDeepLink() {}
  virtual ErrorOr<std::string> Decode(const std::string& uri) = 0;

  // The codec used by IDeepLink.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `IDeepLink` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    IDeepLink* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    IDeepLink* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  IDeepLink() = default;
};
}  // namespace vpn_plugin
#endif  // PIGEON_PLATFORM_API_G_H_
