// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "platform_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace vpn_plugin {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// PlatformErrorResponse

PlatformErrorResponse::PlatformErrorResponse() {}

PlatformErrorResponse::PlatformErrorResponse(
  const PlatformErrorCode* code,
  const EncodableList* field_errors)
 : code_(code ? std::optional<PlatformErrorCode>(*code) : std::nullopt),
    field_errors_(field_errors ? std::optional<EncodableList>(*field_errors) : std::nullopt) {}

const PlatformErrorCode* PlatformErrorResponse::code() const {
  return code_ ? &(*code_) : nullptr;
}

void PlatformErrorResponse::set_code(const PlatformErrorCode* value_arg) {
  code_ = value_arg ? std::optional<PlatformErrorCode>(*value_arg) : std::nullopt;
}

void PlatformErrorResponse::set_code(const PlatformErrorCode& value_arg) {
  code_ = value_arg;
}


const EncodableList* PlatformErrorResponse::field_errors() const {
  return field_errors_ ? &(*field_errors_) : nullptr;
}

void PlatformErrorResponse::set_field_errors(const EncodableList* value_arg) {
  field_errors_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PlatformErrorResponse::set_field_errors(const EncodableList& value_arg) {
  field_errors_ = value_arg;
}


EncodableList PlatformErrorResponse::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(code_ ? CustomEncodableValue(*code_) : EncodableValue());
  list.push_back(field_errors_ ? EncodableValue(*field_errors_) : EncodableValue());
  return list;
}

PlatformErrorResponse PlatformErrorResponse::FromEncodableList(const EncodableList& list) {
  PlatformErrorResponse decoded;
  auto& encodable_code = list[0];
  if (!encodable_code.IsNull()) {
    decoded.set_code(std::any_cast<const PlatformErrorCode&>(std::get<CustomEncodableValue>(encodable_code)));
  }
  auto& encodable_field_errors = list[1];
  if (!encodable_field_errors.IsNull()) {
    decoded.set_field_errors(std::get<EncodableList>(encodable_field_errors));
  }
  return decoded;
}

// PlatformFieldError

PlatformFieldError::PlatformFieldError(
  const PlatformFieldErrorCode& code,
  const PlatformFieldName& field_name)
 : code_(code),
    field_name_(field_name) {}

const PlatformFieldErrorCode& PlatformFieldError::code() const {
  return code_;
}

void PlatformFieldError::set_code(const PlatformFieldErrorCode& value_arg) {
  code_ = value_arg;
}


const PlatformFieldName& PlatformFieldError::field_name() const {
  return field_name_;
}

void PlatformFieldError::set_field_name(const PlatformFieldName& value_arg) {
  field_name_ = value_arg;
}


EncodableList PlatformFieldError::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(CustomEncodableValue(code_));
  list.push_back(CustomEncodableValue(field_name_));
  return list;
}

PlatformFieldError PlatformFieldError::FromEncodableList(const EncodableList& list) {
  PlatformFieldError decoded(
    std::any_cast<const PlatformFieldErrorCode&>(std::get<CustomEncodableValue>(list[0])),
    std::any_cast<const PlatformFieldName&>(std::get<CustomEncodableValue>(list[1])));
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<VpnManagerState>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformErrorCode>(enum_arg_value));
      }
    case 131: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformFieldErrorCode>(enum_arg_value));
      }
    case 132: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<PlatformFieldName>(enum_arg_value));
      }
    case 133: {
        return CustomEncodableValue(PlatformErrorResponse::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(PlatformFieldError::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(VpnManagerState)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<VpnManagerState>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformErrorCode)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformErrorCode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformFieldErrorCode)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformFieldErrorCode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformFieldName)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<PlatformFieldName>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformErrorResponse)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<PlatformErrorResponse>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PlatformFieldError)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<PlatformFieldError>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by IVpnManager.
const flutter::StandardMessageCodec& IVpnManager::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `IVpnManager` to handle messages through the `binary_messenger`.
void IVpnManager::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  IVpnManager* api) {
  IVpnManager::SetUp(binary_messenger, api, "");
}

void IVpnManager::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  IVpnManager* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.start" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_server_name_arg = args.at(0);
          if (encodable_server_name_arg.IsNull()) {
            reply(WrapError("server_name_arg unexpectedly null."));
            return;
          }
          const auto& server_name_arg = std::get<std::string>(encodable_server_name_arg);
          const auto& encodable_config_arg = args.at(1);
          if (encodable_config_arg.IsNull()) {
            reply(WrapError("config_arg unexpectedly null."));
            return;
          }
          const auto& config_arg = std::get<std::string>(encodable_config_arg);
          std::optional<FlutterError> output = api->Start(server_name_arg, config_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.stop" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->Stop();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.updateConfiguration" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_server_name_arg = args.at(0);
          const auto* server_name_arg = std::get_if<std::string>(&encodable_server_name_arg);
          const auto& encodable_config_arg = args.at(1);
          const auto* config_arg = std::get_if<std::string>(&encodable_config_arg);
          std::optional<FlutterError> output = api->UpdateConfiguration(server_name_arg, config_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.getCurrentState" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<VpnManagerState> output = api->GetCurrentState();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue IVpnManager::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue IVpnManager::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

/// The codec used by IDeepLink.
const flutter::StandardMessageCodec& IDeepLink::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `IDeepLink` to handle messages through the `binary_messenger`.
void IDeepLink::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  IDeepLink* api) {
  IDeepLink::SetUp(binary_messenger, api, "");
}

void IDeepLink::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  IDeepLink* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.vpn_plugin.IDeepLink.decode" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_uri_arg = args.at(0);
          if (encodable_uri_arg.IsNull()) {
            reply(WrapError("uri_arg unexpectedly null."));
            return;
          }
          const auto& uri_arg = std::get<std::string>(encodable_uri_arg);
          ErrorOr<std::string> output = api->Decode(uri_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue IDeepLink::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue IDeepLink::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace vpn_plugin
