// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.adguard.trusttunnel.vpn_plugin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PlatformApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * {@template vpn_manager_state}
 * Current state of the platform VPN engine.
 *
 * This enum models the high-level lifecycle of the VPN service/engine as seen
 * from Dart. Implementations may have additional internal substates; they should
 * be mapped onto these public states in a consistent way.
 *
 * ## Typical state flow
 * - [disconnected] → [connecting] → [connected]
 * - On transient failure: [connected] → [waitingForRecovery] → [recovering]
 * - When network is unavailable: [connecting] or [recovering] → [waitingForNetwork]
 *
 * The exact transitions and timing depend on the platform implementation.
 * {@endtemplate}
 */
enum class VpnManagerState(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  WAITING_FOR_RECOVERY(3),
  RECOVERING(4),
  WAITING_FOR_NETWORK(5);

  companion object {
    fun ofRaw(raw: Int): VpnManagerState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * {@template platform_error_code}
 * High-level error category returned by platform implementations.
 *
 * This is intended for coarse error classification suitable for UI messaging
 * and analytics. More specific errors may be provided via [PlatformFieldError].
 * {@endtemplate}
 */
enum class PlatformErrorCode(val raw: Int) {
  UNKNOWN(0);

  companion object {
    fun ofRaw(raw: Int): PlatformErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * {@template platform_field_error_code}
 * Error category for a specific user-visible field.
 *
 * Field errors are typically used to attach validation errors to individual
 * configuration inputs (e.g. invalid IP address).
 * {@endtemplate}
 */
enum class PlatformFieldErrorCode(val raw: Int) {
  FIELD_WRONG_VALUE(0),
  ALREADY_EXISTS(1);

  companion object {
    fun ofRaw(raw: Int): PlatformFieldErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * {@template platform_field_name}
 * Identifies which input field a [PlatformFieldError] refers to.
 *
 * The field set is intentionally limited to values that are meaningful to
 * external consumers and stable across platforms.
 * {@endtemplate}
 */
enum class PlatformFieldName(val raw: Int) {
  IP_ADDRESS(0),
  DOMAIN(1),
  SERVER_NAME(2),
  DNS_SERVERS(3);

  companion object {
    fun ofRaw(raw: Int): PlatformFieldName? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * {@template platform_error_response}
 * Structured error payload returned by platform implementations.
 *
 * This model supports two levels of error reporting:
 * - a top-level [code] for general classification,
 * - optional per-field validation errors in [fieldErrors].
 *
 * Both fields are nullable to support platforms that only provide partial
 * error information.
 * {@endtemplate}
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformErrorResponse (
  /**
   * {@template platform_error_response_code}
   * General error category, if available.
   * {@endtemplate}
   */
  val code: PlatformErrorCode? = null,
  /**
   * {@template platform_error_response_field_errors}
   * Optional list of validation errors tied to individual fields.
   * {@endtemplate}
   */
  val fieldErrors: List<PlatformFieldError?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformErrorResponse {
      val code = pigeonVar_list[0] as PlatformErrorCode?
      val fieldErrors = pigeonVar_list[1] as List<PlatformFieldError?>?
      return PlatformErrorResponse(code, fieldErrors)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      fieldErrors,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformErrorResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * {@template platform_field_error}
 * Validation error associated with a particular configuration field.
 *
 * A field error specifies:
 * - [code] describing the kind of failure,
 * - [fieldName] identifying which field is invalid.
 *
 * This structure is designed for UI clients that want to show inline
 * validation messages next to problematic fields.
 * {@endtemplate}
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformFieldError (
  /**
   * {@template platform_field_error_code_field}
   * Category of the field error.
   * {@endtemplate}
   */
  val code: PlatformFieldErrorCode,
  /**
   * {@template platform_field_error_field_name}
   * Which field the error relates to.
   * {@endtemplate}
   */
  val fieldName: PlatformFieldName
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformFieldError {
      val code = pigeonVar_list[0] as PlatformFieldErrorCode
      val fieldName = pigeonVar_list[1] as PlatformFieldName
      return PlatformFieldError(code, fieldName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      fieldName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PlatformFieldError) {
      return false
    }
    if (this === other) {
      return true
    }
    return PlatformApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PlatformApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VpnManagerState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformErrorCode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformFieldErrorCode.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformFieldName.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformErrorResponse.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformFieldError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VpnManagerState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformErrorCode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformFieldErrorCode -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformFieldName -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformErrorResponse -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PlatformFieldError -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * {@template i_vpn_manager}
 * Host-side VPN manager API.
 *
 * `IVpnManager` is implemented on the platform (host) side and called from Dart.
 * It provides the minimal lifecycle operations required by the plugin:
 * - [start] to start the VPN engine using a prepared configuration string.
 * - [stop] to stop the VPN engine.
 * - [getCurrentState] to query the current engine state.
 *
 * ## Ordering and concurrency
 * [start] and [stop] are executed on a serial background queue (see [TaskQueue]).
 * This ensures:
 * - operations are performed in the order they are invoked,
 * - platform UI threads are not blocked by long-running operations.
 *
 * ## Configuration format
 * The [config] parameter is a backend configuration document (string).
 * Its exact format is defined by the backend and produced on the Dart side
 * (for example by a [ConfigurationEncoder]).
 * {@endtemplate}
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface IVpnManager {
  /**
   * {@template i_vpn_manager_start}
   * Starts the VPN engine using the provided configuration document.
   *
   * [config] must contain a complete backend configuration text. The platform
   * implementation is responsible for:
   * - parsing/validating the configuration,
   * - initiating any required permissions or service start,
   * - transitioning the engine state accordingly.
   *
   * This call is executed on a serial background task queue to avoid blocking
   * the platform UI thread.
   * {@endtemplate}
   */
  fun start(serverName: String, config: String)
  /**
   * {@template i_vpn_manager_stop}
   * Stops the VPN engine.
   *
   * The platform implementation should stop the underlying VPN service/process
   * and transition the engine state to [VpnManagerState.disconnected].
   *
   * This call is executed on a serial background task queue to avoid blocking
   * the platform UI thread.
   * {@endtemplate}
   */
  fun stop()
  /**
   * {@template i_vpn_manager_update_configuration}
   * Updates the iOS system VPN profile or deletes it.
   *
   * The platform implementation should update the iOS system VPN profile
   * if the [serverName] and [config] are specified or delete the profile
   * entirely if one of them is `null`.
   *
   * This method should always be called on stopped VPN engine.
   *
   * This call is executed on a serial background task queue to avoid blocking
   * the platform UI thread.
   * {@endtemplate}
   */
  fun updateConfiguration(serverName: String?, config: String?)
  /**
   * {@template i_vpn_manager_get_current_state}
   * Returns the current VPN engine state.
   *
   * This method is typically used to:
   * - restore UI state after app restart,
   * - confirm whether a start/stop request has taken effect,
   * - diagnose platform-side lifecycle issues.
   * {@endtemplate}
   */
  fun getCurrentState(): VpnManagerState

  companion object {
    /** The codec used by IVpnManager. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `IVpnManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: IVpnManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.start$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serverNameArg = args[0] as String
            val configArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.start(serverNameArg, configArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.stop$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.updateConfiguration$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serverNameArg = args[0] as String?
            val configArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.updateConfiguration(serverNameArg, configArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_plugin.IVpnManager.getCurrentState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCurrentState())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface IDeepLink {
  fun decode(uri: String): String

  companion object {
    /** The codec used by IDeepLink. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `IDeepLink` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: IDeepLink?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_plugin.IDeepLink.decode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.decode(uriArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
