// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPlatformApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPlatformApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPlatformApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPlatformApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPlatformApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPlatformApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// {@template vpn_manager_state}
/// Current state of the platform VPN engine.
///
/// This enum models the high-level lifecycle of the VPN service/engine as seen
/// from Dart. Implementations may have additional internal substates; they should
/// be mapped onto these public states in a consistent way.
///
/// ## Typical state flow
/// - [disconnected] → [connecting] → [connected]
/// - On transient failure: [connected] → [waitingForRecovery] → [recovering]
/// - When network is unavailable: [connecting] or [recovering] → [waitingForNetwork]
///
/// The exact transitions and timing depend on the platform implementation.
/// {@endtemplate}
enum VpnManagerState: Int {
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case waitingForRecovery = 3
  case recovering = 4
  case waitingForNetwork = 5
}

/// {@template platform_error_code}
/// High-level error category returned by platform implementations.
///
/// This is intended for coarse error classification suitable for UI messaging
/// and analytics. More specific errors may be provided via [PlatformFieldError].
/// {@endtemplate}
enum PlatformErrorCode: Int {
  case unknown = 0
}

/// {@template platform_field_error_code}
/// Error category for a specific user-visible field.
///
/// Field errors are typically used to attach validation errors to individual
/// configuration inputs (e.g. invalid IP address).
/// {@endtemplate}
enum PlatformFieldErrorCode: Int {
  case fieldWrongValue = 0
  case alreadyExists = 1
}

/// {@template platform_field_name}
/// Identifies which input field a [PlatformFieldError] refers to.
///
/// The field set is intentionally limited to values that are meaningful to
/// external consumers and stable across platforms.
/// {@endtemplate}
enum PlatformFieldName: Int {
  case ipAddress = 0
  case domain = 1
  case serverName = 2
  case dnsServers = 3
}

/// {@template platform_error_response}
/// Structured error payload returned by platform implementations.
///
/// This model supports two levels of error reporting:
/// - a top-level [code] for general classification,
/// - optional per-field validation errors in [fieldErrors].
///
/// Both fields are nullable to support platforms that only provide partial
/// error information.
/// {@endtemplate}
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformErrorResponse: Hashable {
  /// {@template platform_error_response_code}
  /// General error category, if available.
  /// {@endtemplate}
  var code: PlatformErrorCode? = nil
  /// {@template platform_error_response_field_errors}
  /// Optional list of validation errors tied to individual fields.
  /// {@endtemplate}
  var fieldErrors: [PlatformFieldError?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformErrorResponse? {
    let code: PlatformErrorCode? = nilOrValue(pigeonVar_list[0])
    let fieldErrors: [PlatformFieldError?]? = nilOrValue(pigeonVar_list[1])

    return PlatformErrorResponse(
      code: code,
      fieldErrors: fieldErrors
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      fieldErrors,
    ]
  }
  static func == (lhs: PlatformErrorResponse, rhs: PlatformErrorResponse) -> Bool {
    return deepEqualsPlatformApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// {@template platform_field_error}
/// Validation error associated with a particular configuration field.
///
/// A field error specifies:
/// - [code] describing the kind of failure,
/// - [fieldName] identifying which field is invalid.
///
/// This structure is designed for UI clients that want to show inline
/// validation messages next to problematic fields.
/// {@endtemplate}
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformFieldError: Hashable {
  /// {@template platform_field_error_code_field}
  /// Category of the field error.
  /// {@endtemplate}
  var code: PlatformFieldErrorCode
  /// {@template platform_field_error_field_name}
  /// Which field the error relates to.
  /// {@endtemplate}
  var fieldName: PlatformFieldName


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformFieldError? {
    let code = pigeonVar_list[0] as! PlatformFieldErrorCode
    let fieldName = pigeonVar_list[1] as! PlatformFieldName

    return PlatformFieldError(
      code: code,
      fieldName: fieldName
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      fieldName,
    ]
  }
  static func == (lhs: PlatformFieldError, rhs: PlatformFieldError) -> Bool {
    return deepEqualsPlatformApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPlatformApi(value: toList(), hasher: &hasher)
  }
}

private class PlatformApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VpnManagerState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformFieldErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformFieldName(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return PlatformErrorResponse.fromList(self.readValue() as! [Any?])
    case 134:
      return PlatformFieldError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PlatformApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VpnManagerState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformErrorCode {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformFieldErrorCode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformFieldName {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformErrorResponse {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformFieldError {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PlatformApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PlatformApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PlatformApiPigeonCodecWriter(data: data)
  }
}

class PlatformApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PlatformApiPigeonCodec(readerWriter: PlatformApiPigeonCodecReaderWriter())
}

/// {@template i_vpn_manager}
/// Host-side VPN manager API.
///
/// `IVpnManager` is implemented on the platform (host) side and called from Dart.
/// It provides the minimal lifecycle operations required by the plugin:
/// - [start] to start the VPN engine using a prepared configuration string.
/// - [stop] to stop the VPN engine.
/// - [getCurrentState] to query the current engine state.
///
/// ## Ordering and concurrency
/// [start] and [stop] are executed on a serial background queue (see [TaskQueue]).
/// This ensures:
/// - operations are performed in the order they are invoked,
/// - platform UI threads are not blocked by long-running operations.
///
/// ## Configuration format
/// The [config] parameter is a backend configuration document (string).
/// Its exact format is defined by the backend and produced on the Dart side
/// (for example by a [ConfigurationEncoder]).
/// {@endtemplate}
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IVpnManager {
  /// {@template i_vpn_manager_start}
  /// Starts the VPN engine using the provided configuration document.
  ///
  /// [config] must contain a complete backend configuration text. The platform
  /// implementation is responsible for:
  /// - parsing/validating the configuration,
  /// - initiating any required permissions or service start,
  /// - transitioning the engine state accordingly.
  ///
  /// This call is executed on a serial background task queue to avoid blocking
  /// the platform UI thread.
  /// {@endtemplate}
  func start(serverName: String, config: String) throws
  /// {@template i_vpn_manager_stop}
  /// Stops the VPN engine.
  ///
  /// The platform implementation should stop the underlying VPN service/process
  /// and transition the engine state to [VpnManagerState.disconnected].
  ///
  /// This call is executed on a serial background task queue to avoid blocking
  /// the platform UI thread.
  /// {@endtemplate}
  func stop() throws
  /// {@template i_vpn_manager_update_configuration}
  /// Updates the iOS system VPN profile or deletes it.
  ///
  /// The platform implementation should update the iOS system VPN profile
  /// if the [serverName] and [config] are specified or delete the profile
  /// entirely if one of them is `null`.
  ///
  /// This method should always be called on stopped VPN engine.
  ///
  /// This call is executed on a serial background task queue to avoid blocking
  /// the platform UI thread.
  /// {@endtemplate}
  func updateConfiguration(serverName: String?, config: String?) throws
  /// {@template i_vpn_manager_get_current_state}
  /// Returns the current VPN engine state.
  ///
  /// This method is typically used to:
  /// - restore UI state after app restart,
  /// - confirm whether a start/stop request has taken effect,
  /// - diagnose platform-side lifecycle issues.
  /// {@endtemplate}
  func getCurrentState() throws -> VpnManagerState
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IVpnManagerSetup {
  static var codec: FlutterStandardMessageCodec { PlatformApiPigeonCodec.shared }
  /// Sets up an instance of `IVpnManager` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IVpnManager?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    /// {@template i_vpn_manager_start}
    /// Starts the VPN engine using the provided configuration document.
    ///
    /// [config] must contain a complete backend configuration text. The platform
    /// implementation is responsible for:
    /// - parsing/validating the configuration,
    /// - initiating any required permissions or service start,
    /// - transitioning the engine state accordingly.
    ///
    /// This call is executed on a serial background task queue to avoid blocking
    /// the platform UI thread.
    /// {@endtemplate}
    let startChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IVpnManager.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IVpnManager.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serverNameArg = args[0] as! String
        let configArg = args[1] as! String
        do {
          try api.start(serverName: serverNameArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// {@template i_vpn_manager_stop}
    /// Stops the VPN engine.
    ///
    /// The platform implementation should stop the underlying VPN service/process
    /// and transition the engine state to [VpnManagerState.disconnected].
    ///
    /// This call is executed on a serial background task queue to avoid blocking
    /// the platform UI thread.
    /// {@endtemplate}
    let stopChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IVpnManager.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IVpnManager.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// {@template i_vpn_manager_update_configuration}
    /// Updates the iOS system VPN profile or deletes it.
    ///
    /// The platform implementation should update the iOS system VPN profile
    /// if the [serverName] and [config] are specified or delete the profile
    /// entirely if one of them is `null`.
    ///
    /// This method should always be called on stopped VPN engine.
    ///
    /// This call is executed on a serial background task queue to avoid blocking
    /// the platform UI thread.
    /// {@endtemplate}
    let updateConfigurationChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IVpnManager.updateConfiguration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IVpnManager.updateConfiguration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      updateConfigurationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serverNameArg: String? = nilOrValue(args[0])
        let configArg: String? = nilOrValue(args[1])
        do {
          try api.updateConfiguration(serverName: serverNameArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateConfigurationChannel.setMessageHandler(nil)
    }
    /// {@template i_vpn_manager_get_current_state}
    /// Returns the current VPN engine state.
    ///
    /// This method is typically used to:
    /// - restore UI state after app restart,
    /// - confirm whether a start/stop request has taken effect,
    /// - diagnose platform-side lifecycle issues.
    /// {@endtemplate}
    let getCurrentStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IVpnManager.getCurrentState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCurrentState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCurrentStateChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IDeepLink {
  func decode(uri: String) throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IDeepLinkSetup {
  static var codec: FlutterStandardMessageCodec { PlatformApiPigeonCodec.shared }
  /// Sets up an instance of `IDeepLink` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IDeepLink?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let decodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.vpn_plugin.IDeepLink.decode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriArg = args[0] as! String
        do {
          let result = try api.decode(uri: uriArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      decodeChannel.setMessageHandler(nil)
    }
  }
}
